apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: certificates
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Before Traefik
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        
        global:
          leaderElection:
            namespace: cert-manager
        
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        
        cainjector:
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
        
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Required for CRDs