apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: security
  annotations:
    argocd.argoproj.io/sync-wave: "-4"  # Deploy before everything else
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.2
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets-controller
      values: |
        fullnameOverride: sealed-secrets-controller
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
            cpu: 50m
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true