apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: networking
  finalizers: []
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/sprevacomm/homelab2.git
      targetRevision: main
      ref: values
    - repoURL: https://helm.traefik.io/traefik
      targetRevision: 36.3.0
      chart: traefik
      helm:
        releaseName: traefik
        valueFiles:
          - $values/infrastructure/networking/traefik/values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10