# ArgoCD Helm Values
# ArgoCD v8.1.3 configuration for homelab

global:
  domain: argocd.susdomain.name
  logging:
    format: json
    level: info

server:
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      traefik.ingress.kubernetes.io/router.middlewares: traefik-default-headers@kubernetescrd
    hosts:
      - argocd.susdomain.name
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - argocd.susdomain.name
        secretName: argocd-server-tls
  
  # Disable internal TLS
  insecure: true

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

repoServer:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

applicationSet:
  enabled: true
  replicas: 1

dex:
  enabled: false

redis:
  enabled: true

redis-ha:
  enabled: false

notifications:
  enabled: true
  argocdUrl: https://argocd.susdomain.name

configs:
  params:
    server.insecure: true
    controller.diff.server.side: true
    controller.operation.processors: 10
    controller.status.processors: 20
    controller.self.heal.timeout.seconds: 5
    controller.repo.server.timeout.seconds: 60
    application.resourceTrackingMethod: annotation
  
  cm:
    url: https://argocd.susdomain.name
    application.instanceLabelKey: argocd.argoproj.io/instance
    server.rbac.log.enforce.enable: false
    exec.enabled: true
    admin.enabled: true
    # Enable Helm support in Kustomize
    kustomize.buildOptions: --enable-helm
    timeout.reconciliation: 180s
    timeout.hard.reconciliation: 0s
    
    # Add repositories
    repositories: |
      - type: git
        url: https://github.com/seanpatnode/homelab2.git
        name: homelab2
      - type: helm
        url: https://metallb.github.io/metallb
        name: metallb
      - type: helm
        url: https://helm.traefik.io/traefik
        name: traefik
      - type: helm
        url: https://argoproj.github.io/argo-helm
        name: argo
  
  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, projects, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, *, allow
      
      g, argocd-admins, role:admin
  
  # Default admin password (change after first login)
  # This is 'admin' hashed with bcrypt
  secret:
    argocdServerAdminPassword: $2a$10$rBk7lknLB7kRAqpFH6BDLe/jGoTKB2H4NOl4Y6Rb0pBE5oUEbnJcS