apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: load-balancer
  finalizers: []
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.2
    chart: metallb
    helm:
      releaseName: metallb
      valueFiles:
        - values.yaml
      values: |
        controller:
          image:
            repository: quay.io/metallb/controller
            tag: v0.15.2
        speaker:
          image:
            repository: quay.io/metallb/speaker
            tag: v0.15.2
        prometheus:
          serviceMonitor:
            enabled: false
        crds:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10